spring:
  profiles:
    active: usage_message
    rabbitmq:
    host: localhost
    port: 8090
    username: guest
    password: JAmbg172*

logging:
  level:
    org: ERROR
    

tutorial:
  client:
    duration: 10000
  
